name: autosubmit
channels:
- conda-forge

dependencies:
- nose
- nose-cov
- paramiko
- pydotplus
- python-dateutil
- pyparsing
- numpy
- matplotlib
- pip
- mock
- portalocker
- networkx
- python=2.7
- pip:
  - bscearth.utils
  - Xlib 
  - requests
  - typing
