confIg:
  AUTOSUBMIT_VERSION: 4.0
  MAXWAITINGJOBS: 20
  TOTALJOBS: 20
  SAFETYSLEEPTIME: 10
  RETRIALS: 0
wrappers:
  wrapper_sim:
    TYPE: "vertical"
    JOBS_IN_WRAPPER: "SIM"
mail:
  NOTIFICATIONS: False
  TO: daniel.beltran@bsc.es
storage:
  TYPE: "pkl"
  COPY_REMOTE_LOGS: True