confIg:
  AUTOSUBMIT_VERSION: 4.0.0
  MAXWAITINGJOBS: 20
  TOTALJOBS: 20
  SAFETYSLEEPTIME: 10
  RETRIALS: 0
  PRESUBMISSION: 'true'
wrappers:
  wrapper_sim:
    TYPE: "vertical"
    JOBS_IN_WRAPPER: "SIM"
mail:
  NOTIFICATIONS: False
  TO:
storage:
  TYPE: "pkl"
  COPY_REMOTE_LOGS: True